# Generated by Django 4.2.1 on 2023-06-07 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sap', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('water_amount', models.DecimalField(decimal_places=3, max_digits=5)),
                ('lye_amount', models.DecimalField(decimal_places=3, max_digits=5)),
                ('super_fat', models.DecimalField(decimal_places=3, max_digits=5)),
                ('description', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Soaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=5)),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soapdishapi.oil')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_oils', to='soapdishapi.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', through='soapdishapi.Favorite', to='soapdishapi.soaper'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='soapdishapi.soaper'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='oils',
            field=models.ManyToManyField(related_name='oils', through='soapdishapi.RecipeOil', to='soapdishapi.oil'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soapdishapi.recipe'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soapdishapi.soaper'),
        ),
    ]
